### PR TITLE
Refactor 1

### PR DESCRIPTION
**Pull request by andyjac**
Not perfect, but this is sort of what I have in mind. Run `node lib/main.js` from project root to run it. I had to use fs.readFileSync because I couldn't figure out how to make async work, but we can tackle that tomorrow (or later tonight if I'm feeling ambitious). Eventually it would be nice to have an `index.js` file in the root folder which takes args from the command line (a bitmap file as its first arg and a transform to run as its second), but this is a good start for now. Let me know what you guys think. I think this should make it easier to test our individual functions.

### CODE REVIEW

**Comment by andyjac** [comment]
Update: Got async to work using an event emitter and added some terminal log updates just for fun!

**Comment by andyjac** [comment]
Update: Added `index.js` as an init file to run the program. It takes two args, the file to read and the transform to run. Can be run from the command line as follows: `node index.js bitmap.bmp randomize`

**Comment by jayspringate** [comment]
Wow that's awesome! Great work!

**Comment by andyjac** [comment]
Thanks! I got your test running with the new version and figured out how to use done() in the before block in order to do async set up.

**Comment by jayspringate** [comment]
Nice! I'll probably be at the coworking space around 5 or 6 to take a look
at it.

**Pull request merged**
